name: Refresh Data

on:
  workflow_dispatch:
  schedule:
    # run on tuesdays at 16:00 UTC (1 hour after wow weekly reset)
    # runs on the last commit on the default branch
    - cron: "0 16 * * 2"

jobs:
  refresh:
    name: Refresh item data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scrape code
        uses: actions/checkout@v3
        with:
          repository: t-mart/item-version-scrape
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn" # this is why pnpm setup goes first. will fail otherwise

      - name: Refresh Data.lua
        run: yarn main

      - name: Upload generated lua artifact
        uses: actions/upload-artifact@v3
        with:
          name: Data.lua
          path: dist/Data.lua

  commit:
    name: Commit new item data
    runs-on: ubuntu-latest
    needs: refresh
    outputs:
      refreshed-data-git-ref: ${{ steps.get-refreshed-data-git-ref.outputs.git-ref }}
    steps:
      - name: Checkout addon code
        uses: actions/checkout@v3

      - name: Clear old data
        run: |
          rm ItemVersion/Data.lua

      - name: Download generated lua artifact
        uses: actions/download-artifact@v3
        with:
          name: Data.lua
          path: ItemVersion/

      - name: Git Commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ItemVersion/Data.lua
          git commit -m "Refresh item data"

      - name: Push changes
        uses: ad-m/github-push-action@master

      - name: Push changes
        id: get-refreshed-data-git-ref
        run: |
          echo "git-ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  release:
    needs: commit
    uses: ./.github/workflows/release.yml
    with:
      git-ref: ${{ needs.commit.outputs.refreshed-data-git-ref }}
      release-type: "release"
    secrets: inherit
