name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "The type of wap release to perform (or none at all)"
        type: choice
        options:
          - "none"
          - "alpha"
          - "beta"
          - "release"
        required: false
        default: "beta"
  workflow_call:
    inputs:
      git-ref:
        type: string
        required: false
        default: ''
      release-type:
        type: string
        required: false
        default: "beta"
    secrets:
      CF_API_KEY:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.git-ref }}
        token: ${{ secrets.GH_PAT }}

    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install calver-cli
      shell: bash
      run: |
        npm install --global calver-cli

    - name: Determine next version
      id: next-version
      shell: bash
      run: |
        LAST_VERSION=$(jq <"wap.json" ".version" --raw-output)
        echo "Last version was $LAST_VERSION"
        NEXT_VERSION=$(calver inc --format yyyy.0w.patch --levels calendar.patch $LAST_VERSION)
        echo "Next version is $NEXT_VERSION"
        echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

    - name: Update wap.json version
      shell: bash
      run: |
        jq  ".version = \"$NEXT_VERSION\"" <wap.json >wap-next.json
        mv wap-next.json wap.json
      env:
        NEXT_VERSION: "${{ steps.next-version.outputs.version }}"

    - name: Commit, tag, and push
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add wap.json
        git commit -m "Release $NEXT_VERSION"
        git tag -a "$NEXT_VERSION" -m "Release $NEXT_VERSION"
        git push --atomic origin  "${{ github.ref_name }}" "$NEXT_VERSION"
      env:
        NEXT_VERSION: "${{ steps.next-version.outputs.version }}"

    - name: wap
      uses: t-mart/wap-action@master
      with:
        release-type: ${{ inputs.release-type }}
        curseforge-token: ${{ secrets.CF_API_KEY }}

    - name: GH Release
      run: |
        gh release create "$NEXT_VERSION" dist/*.zip
      env:
        NEXT_VERSION: "${{ steps.next-version.outputs.version }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
